"""FIX 3 — secret-leakage audit for the LIVE map-key bypass shape.

Asserts the reconciled/generated bypass secret (the ``protectionBypass`` MAP
KEY) never appears in durable project state, the conversation registry, the
OperationResult error/repr surface, logger output, or deployment metadata --
only in the caller-facing success ``data`` (which the secure store persists).

No real Vercel, no network, no Telegram.
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

import pytest

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE.parent))

from r1_harness import LocalR1Scenario, patch_qa_boundaries  # noqa: E402
from test_r1_phase_g_full_story import TURN_1, TURN_2  # noqa: E402


def _drive(h: LocalR1Scenario) -> str:
    h.set_router_decision("CREATE_PROJECT", confidence="high",
                          proposed_new_project_name=None)
    h.send_user_message(TURN_1)
    h.set_intake_response(name="cozyreadingspace", what="x", why="y",
                          readiness="DISCOVERY_READY", clarification_needed=False)
    h.send_user_message(TURN_2)
    return h.current_project_id


def _all_persisted_text(root: Path) -> str:
    """Every persisted artifact under the scenario root EXCEPT the dedicated
    secure bypass store (the ONE legitimate place the secret is persisted)."""
    store_dir = (root / "hermes-home" / "vercel-bypass").resolve()
    chunks = []
    for path in root.rglob("*"):
        if not path.is_file() or path.suffix not in (".json", ".txt", ".log"):
            continue
        try:
            if store_dir in path.resolve().parents:
                continue
        except Exception:
            pass
        try:
            chunks.append(path.read_text(encoding="utf-8", errors="replace"))
        except Exception:
            pass
    return "\n".join(chunks)


def test_secret_never_in_state_registry_telegram_logs_or_errors(tmp_path, monkeypatch, caplog):
    patch_qa_boundaries(monkeypatch)
    h = LocalR1Scenario(tmp_path)
    pid = _drive(h)
    with caplog.at_level(logging.DEBUG):
        assert h.preview.run_owned(pid, h.runner.create_workspace(pid)).success

    secret = h.bypass_store.get("prj_1")
    assert secret

    # 1. Durable PROJECT STATE never contains the secret.
    state_raw = (h.state_root / f"{pid}.json").read_text(encoding="utf-8")
    assert secret not in state_raw
    # 2. Conversation registry never contains the secret.
    reg_raw = (h.state_root / "conversations" / "555.json").read_text(encoding="utf-8")
    assert secret not in reg_raw
    # 3. Deployment metadata persisted in state is clean too (covered by (1)).
    state = h.project_state(pid)
    assert secret not in str(state.deployment)
    # 4. Telegram messages never contain the secret.
    for _chat, text in h.telegram.text_calls:
        assert secret not in text
    for _chat, _path, caption in h.telegram.photo_calls:
        assert secret not in caption
    # 5. Logs (DEBUG captured) never contain the secret.
    assert secret not in caplog.text
    # 6. Every persisted artifact under the scenario root is clean.
    assert secret not in _all_persisted_text(tmp_path)
    # 7. The store's public repr never contains the secret.
    assert secret not in repr(h.bypass_store)


def test_reconcile_failure_error_strings_never_leak(tmp_path, monkeypatch):
    """Fail-closed reconciliation paths must not echo any secret."""
    patch_qa_boundaries(monkeypatch)
    h = LocalR1Scenario(tmp_path)
    pid = _drive(h)
    assert h.preview.run_owned(pid, h.runner.create_workspace(pid)).success
    secret = h.bypass_store.get("prj_1")
    assert secret

    # Now make the REMOTE read ambiguous and wipe local -> recovery must fail
    # closed with a sanitized code, never the secret.
    h.vercel.remote_bypass = "AMBIGUOUS"
    h._wipe_bypass_store()
    result = h.preview.run_owned(pid, h.runner.create_workspace(pid))
    assert not result.success
    assert result.error_code == "AMBIGUOUS_BYPASS_PROVISION"
    assert secret not in str(result)
    assert secret not in repr(result)
    assert secret not in (result.error or "")
